# permissions for end users to view WeGO applications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-viewer-role
rules:
  - apiGroups: ["wego.weave.works", "helm.toolkit.fluxcd.io", "kustomize.toolkit.fluxcd.io", "notification.toolkit.fluxcd.io", "source.toolkit.fluxcd.io", "image.toolkit.fluxcd.io", "notification.toolkit.fluxcd.io"]
    resources: ["apps", "helmreleases", "kustomizations", "alerts", "buckets", "gitrepositories", "helmcharts", "helmrepositories", "imagepolicies", "imagerepositories", "imageupdateautomations", "providers", "receivers"]
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - wego.weave.works
    resources:
      - apps/status
    verbs:
      - get
