version: 2

# https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/
defaults: &defaults
  docker:
    - image: weaveworks/wks-build:ci-cf3a6fc
      environment:
        GOPATH: /go/
        SRCDIR: /go/src/github.com/weaveworks/wks
  working_directory: /go/src/github.com/weaveworks/wks

workflows:
  version: 2
  test-build-deploy:
    jobs:
    - build
    - smoke-test:
        requires:
        - build

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
            make lint
            make binaries
      - persist_to_workspace:
          root: .
          paths:
          - cmd/wksctl/wksctl

  smoke-test:
    machine:
      docker_layer_caching: true
    environment:
      GOPATH: /home/circleci/go
      SRCDIR: /home/circleci/go/src/github.com/weaveworks/wks
    working_directory: /home/circleci/go/src/github.com/weaveworks/wks
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: /tmp/workspace/cmd/wksctl/wksctl version
      - run: env
      - run:
          name: Create VMs
          command: docker run --env-file <(env|grep -E 'CIRCLE|SECRET|SRCDIR') -v /root:/root -v /tmp:/tmp -v /home/circleci:/home/circleci --entrypoint=$SRCDIR/bin/provision_test_vms.sh weaveworks/wks-build:latest
      - run: sudo find / -name .ssh
      - run:
          name: Run integration tests
          command: |
            docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD" quay.io
            go test -v ./test -args -run.interactive -cmd /tmp/workspace/cmd/wksctl/wksctl
      - run:
          name: Destroy VMs
          command: docker run --env-file <(env|grep -E 'CIRCLE|SECRET|SRCDIR') -v /root:/root -v /tmp:/tmp -v /home/circleci:/home/circleci --entrypoint=$SRCDIR/bin/circle-destroy-vms weaveworks/wks-build:latest
