version: 2

# https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/
defaults: &defaults
  docker:
    - image: weaveworks/wks-build:ci-cf3a6fc
      environment:
        GOPATH: /go/
        SRCDIR: /go/src/github.com/weaveworks/wks
  working_directory: /go/src/github.com/weaveworks/wks

workflows:
  version: 2
  test-build-deploy:
    jobs:
    - build
    - smoke-test

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: make binaries

  smoke-test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create VMs
          command: bin/provision_test_vms.sh
      - run:
          name: Destroy VMs
          command: bin/circle-destroy-vms
