version: 2

# https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/
defaults: &defaults
  docker:
    - image: quay.io/wks/build:master-7421a07b
      environment:
        GOPATH: /go/
        SRCDIR: /go/src/github.com/weaveworks/wks
  working_directory: /go/src/github.com/weaveworks/wks

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - container-tests: {}
      - unit-tests: {}
      - integration-tests:
          requires:
            - build

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker

      - run:
          command: |
            make
            make lint
      - deploy:
          name: Push wksctl to S3
          command: |
            TAG=${CIRCLE_TAG}
            if [ -z "$TAG" ]; then
              TAG=$(./tools/image-tag)
            fi
            if [ -z "${CI_BRANCH}" -o "${CI_BRANCH}" == "master" ]; then
              # aws gets its credential through the AWS_ACCESS_KEY_ID and
              # AWS_SECRET_ACCESS_KEY environment variables.
              aws s3 cp cmd/wksctl/wksctl s3://weaveworks-wks/wksctl-${TAG}
            fi
      - persist_to_workspace:
          root: .
          paths:
          - kubectl
          - cmd/wksctl/wksctl
      - run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" quay.io
      - run: make push

  unit-tests:
    docker:
      - image: quay.io/wks/build:master-7421a07b
        environment:
          GOPATH: /go
          SRCDIR: /go/src/github.com/weaveworks/wks
    working_directory: /go/src/github.com/weaveworks/wks
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            sudo curl -o kubectl https://storage.googleapis.com/kubernetes-release/release/v1.10.5/bin/linux/amd64/kubectl
            sudo chmod +x kubectl
            sudo cp kubectl /usr/local/bin
      - run:
          name: Run unit tests
          command: |
            go version
            make unit-tests

  container-tests:
    docker:
      - image: quay.io/wks/build:master-7421a07b
        environment:
          GOPATH: /go
          SRCDIR: /go/src/github.com/weaveworks/wks
    working_directory: /go/src/github.com/weaveworks/wks
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Run container tests
          command: |
            go version
            make container-tests

  integration-tests:
    docker:
      - image: quay.io/wks/build:master-7421a07b
        environment:
          GOVERSION: 1.11.2
          GOPATH: /go/
          SRCDIR: /go/src/github.com/weaveworks/wks
    working_directory: /go/src/github.com/weaveworks/wks
    steps:
      - checkout
      - setup_remote_docker

      - attach_workspace:
          at: /tmp/workspace
      - run: /tmp/workspace/cmd/wksctl/wksctl version
      - run: env

      - run:
          name: Install kubectl
          command: |
            sudo curl -o kubectl https://storage.googleapis.com/kubernetes-release/release/v1.10.5/bin/linux/amd64/kubectl
            sudo chmod +x kubectl
            sudo cp kubectl /usr/local/bin

      - run:
          name: Create VMs
          command: $SRCDIR/test/integration/bin/up.sh

      - run:
          name: Run integration tests
          command: $SRCDIR/test/integration/bin/test.sh

      - run:
          name: Destroy VMs
          command: $SRCDIR/test/integration/bin/down.sh
