version: 2

# https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/
defaults: &defaults
  docker:
    - image: weaveworks/wks-build:ci-cf3a6fc
      environment:
        GOPATH: /go/
        SRCDIR: /go/src/github.com/weaveworks/wks
  working_directory: /go/src/github.com/weaveworks/wks

workflows:
  version: 2
  test-build-deploy:
    jobs:
    - build
    - smoke-test

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
            make lint
            make binaries

  smoke-test:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.09.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Create VMs
          command: bin/provision_test_vms.sh
      - run:
          name: Run integration tests
          command: |
            make binaries
            go test -v ./test -args -run.interactive -cmd $PWD/cmd/wksctl/wksctl
      - run:
          name: Destroy VMs
          command: bin/circle-destroy-vms
