version: 2

# https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/
defaults: &defaults
  docker:
    - image: quay.io/wks/build:master-7421a07b
      environment:
        GOPATH: /go/
        SRCDIR: /go/src/github.com/weaveworks/wks
  working_directory: /go/src/github.com/weaveworks/wks

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - container-tests: {}
      - unit-tests: {}
      - integration-tests:
          requires:
            - build

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker

      - run:
          command: |
            make
            make lint
      - deploy:
          name: Push wksctl to S3
          command: |
            TAG=${CIRCLE_TAG}
            if [ -z "$TAG" ]; then
              TAG=$(./tools/image-tag)
            fi
            if [ -z "${CI_BRANCH}" -o "${CI_BRANCH}" == "master" ]; then
              # aws gets its credential through the AWS_ACCESS_KEY_ID and
              # AWS_SECRET_ACCESS_KEY environment variables.
              aws s3 cp cmd/wksctl/wksctl s3://weaveworks-wks/wksctl-${TAG}
            fi
      - persist_to_workspace:
          root: .
          paths:
          - kubectl
          - cmd/wksctl/wksctl
      - run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" quay.io
      - run: make push

  unit-tests:
    docker:
      - image: quay.io/wks/build:master-7421a07b
        environment:
          GOPATH: /go
          SRCDIR: /go/src/github.com/weaveworks/wks
          KUBECTL_URL: https://dl.k8s.io/v1.10.5/kubernetes-client-linux-amd64.tar.gz
          KUBECTL_CHECKSUM: da9d557989a0b9671a610f21642052febb8f70c3cf144c98a8a4f7ecab6bafe2
    working_directory: /go/src/github.com/weaveworks/wks
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -L $KUBECTL_URL -o kubectl.tar.gz
            echo "$KUBECTL_CHECKSUM kubectl.tar.gz" | sha256sum -c
            tar xvzf kubectl.tar.gz --strip-components=3
            sudo mv kubectl /usr/local/bin

      - run:
          name: Run unit tests
          command: |
            go version
            make unit-tests

  container-tests:
    machine:
      docker_layer_caching: true
    environment:
      GOURL: https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz
      GOCHECKSUM: 1dfe664fa3d8ad714bbd15a36627992effd150ddabd7523931f077b3926d736d
      GOROOT: /home/circleci/goroot
      GOPATH: /home/circleci/go
      SRCDIR: /home/circleci/go/src/github.com/weaveworks/wks
    working_directory: /home/circleci/go/src/github.com/weaveworks/wks
    steps:
      - checkout
      - run:
          name: Install go
          command: |
            (cd ~ && curl -L $GOURL -o go.tar.gz && echo "$GOCHECKSUM go.tar.gz" | sha256sum -c)
            mkdir -p $GOROOT && tar xf ~/go.tar.gz -C $GOROOT --strip-components 1

      - run:
          name: Run container tests
          command: |
            export PATH=$GOROOT/bin:$PATH
            go version
            make container-tests

  integration-tests:
    docker:
      - image: quay.io/wks/build:master-7421a07b
        environment:
          GOPATH: /go/
          SRCDIR: /go/src/github.com/weaveworks/wks
          KUBECTL_URL: https://dl.k8s.io/v1.10.5/kubernetes-client-linux-amd64.tar.gz
          KUBECTL_CHECKSUM: da9d557989a0b9671a610f21642052febb8f70c3cf144c98a8a4f7ecab6bafe2
    working_directory: /go/src/github.com/weaveworks/wks
    steps:
      - checkout
      - setup_remote_docker

      - attach_workspace:
          at: /tmp/workspace
      - run: /tmp/workspace/cmd/wksctl/wksctl version
      - run: env

      - run:
          name: Install kubectl
          command: |
            curl -L $KUBECTL_URL -o kubectl.tar.gz
            echo "$KUBECTL_CHECKSUM kubectl.tar.gz" | sha256sum -c
            tar xvzf kubectl.tar.gz --strip-components=3
            sudo mv kubectl /usr/local/bin

      - run:
          name: Create VMs
          command: CREATE_IMAGE=0 IMAGE_NAME=ubuntu-os-cloud/ubuntu-1804-bionic-v20190530 $SRCDIR/test/integration/bin/up.sh

      - run:
          name: Run integration tests
          command: $SRCDIR/test/integration/bin/test.sh

      - run:
          name: Destroy VMs
          command: IMAGE_NAME=ubuntu-os-cloud/ubuntu-1804-bionic-v20190530 $SRCDIR/test/integration/bin/down.sh
          when: always
