nameOverride: ""
fullnameOverride: ""

enabled: true
image:
  repository: weaveworks/wkp-ui-server
  tag: latest
  pullSecrets: []
  pullPolicy: IfNotPresent
ingress:
  enabled: false
  annotations: {}
  labels: {}
  path: /
  hosts:
    - chart-example.local
  tls: []
service:4
  name: wkp-ui-server
  port: 80
config: # remember to consult `app/ui/src/entities/config.ts` before making any changes to this file. (see see https://github.com/weaveworks/wkp-ui/issues/200)
  gitRepo:
    # e.g. git@github.com:weaveworks/wkp-core.git
    url: ''
    branch: ''
    deployKeySecret:
      name: 'wkp-ui-git-deploy-key'
      key: 'gitDeployKey'
    # Provide overrides to drilldownlinks, these are automatically
    # calculated for known providers like GitHub
    drilldownLinks:
      repo: ''
      # Handlebar template that will be provided with {{ branch }}
      # E.g. https://mygit.com/foo/branches/{{ branch }}
      branch: ''
      # Handlebar template that will be provided with {{ commit }}
      # E.g. https://mygit.com/foo/commits/{{ commit }}
      commit: ''
  datasources:
    alertmanager: ''
    prometheus: ''
  drilldownLinks:
    # Set the url values to make the drilldown links work
    cluster_resources:
      url: ''
    node_resources:
      queryParam: instance
      url: ''
    alertmanager_dashboard:
      url: ''
  resources:
    cluster_cpu_utilisation:
      label: CPU
      query: sum (rate (container_cpu_usage_seconds_total{id="/"}[5m])) / sum (machine_cpu_cores)
      drilldownLink: cluster_resources
    cluster_memory_utilisation:
      label: Memory
      query: sum (container_memory_working_set_bytes{id="/"}) / sum (machine_memory_bytes)
      drilldownLink: cluster_resources
    node_cpu_utilisation:
      label: CPU
      query: node:node_cpu_utilisation:avg1m
    node_memory_utilisation:
      label: Memory
      query: node:node_memory_utilisation:ratio
    node_pods_count:
      label: Pods
      query: sum (kube_pod_info) by (__name__,node)
  clusterInfo:
    name: WKP/My Cluster
    provider: ''
    regions: ''
  homepage:
    alertNotifications:
      enabled: true
      rotate: true
      rotationInterval: 5s
      pollInterval: 15s
      displayLimit: 1
      drilldownLink: alertmanager_dashboard
    clusterResources:
      enabled: true
      pollInterval: 15s
      dials:
      - resource: cluster_cpu_utilisation
      - resource: cluster_memory_utilisation
    clusterComponents:
      enabled: true
      pollInterval: 5s
      configMap:
        name: 'foo'
        key: components.json
    repoBranches:
      enabled: true
      pollInterval: 10s
    nodesOverview:
      enabled: true
      title: All Nodes
      pollInterval: 15s
      # Must have at most 2 sparklines for the good looks
      sparklines:
      - resource: node_cpu_utilisation
      - resource: node_memory_utilisation
      singlestat: node_pods_count
      drilldownLink: node_resources
