nameOverride: ""
fullnameOverride: ""

enabled: true
image:
  repository: weaveworks/wkp-ui-server
  tag: master-b85d876
  pullSecrets: []
  pullPolicy: IfNotPresent
ingress:
  enabled: false
  annotations: {}
  labels: {}
  path: /
  hosts:
    - chart-example.local
  tls: []
service:
  name: wkp-ui-server
  port: 80
config:
  datasources:
    alertmanager: http://prometheus-operator-alertmanager.monitoring.svc:9093/api/v1
    prometheus: http://prometheus-operator-prometheus.monitoring.svc:9090/api/v1
  clusterInfo:
    name: WKP/My Cluster
    provider: ''
    regions: ''
  homepage:
    alertNotifications:
      enabled: true
      rotate: true
      rotationInterval: 5s
      pollInterval: 15s
      displayLimit: 1
      drilldownLink:
        url: http://wkp-ui-grafana.monitoring.svc:80/d/alerts/prometheus-alertmanager
    clusterResources:
      enabled: true
      pollInterval: 15s
      dials:
      - name: CPU
        query: sum (rate (container_cpu_usage_seconds_total{id="/"}[5m])) / sum (machine_cpu_cores)
        drilldownLink:
          url: http://wkp-ui-grafana.monitoring.svc:80/d/all-nodes-resources/kubernetes-all-nodes-resources
      - name: Memory
        query: sum (container_memory_working_set_bytes{id="/"}) / sum (machine_memory_bytes)
        drilldownLink:
          url: http://wkp-ui-grafana.monitoring.svc:80/d/all-nodes-resources/kubernetes-all-nodes-resources
    nodesOverview:
      enabled: true
      title: All Nodes
      pollInterval: 15s
      # Must have at most 2 sparklines for the good looks
      sparklines:
      - name: CPU
        query: node:node_cpu_utilisation:avg1m
      - name: Memory
        query: node:node_memory_utilisation:ratio
      singlestat:
        name: Pods
        query: sum (kube_pod_info) by (__name__,node)
      drilldownLink:
        nodeQueryParam: instance
        url: http://wkp-ui-grafana.monitoring.svc:80/d/single-node-resources/kubernetes-single-node-resources
    clusterComponents:
      enabled: true
      components:
      - name: wkp-flux-bootstrap
      - name: wkp-flux-helm-operator
      - name: wkp-tiller
      - name: wkp-external-dns
      - name: wkp-prometheus
        endpoints:
        - name: 'Prometheus'
          url: '/prometheus'
        - name: 'Alert manager'
          url: '/alertmanager'
      - name: wkp-ui
      - name: wkp-grafana
        endpoints:
        - name: 'Grafana'
          url: '/grafana'

