---
apiVersion: v1
kind: Service
metadata:
  name: gitops-repo-broker
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    name: gitops-repo-broker
  type: ClusterIP
