name: Run integration tests command
on:
  repository_dispatch:
    types: [test-command]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Run Kubernetes tools
        id: run-the-tests
        env:
          CIRCLECI_TOKEN: ${{ secrets.WEAVEWORKSBOT_CIRCLECI_TOKEN }}
        run: |
          set -x

          branch="${{ github.event.client_payload.pull_request.head.ref }}"
          job="${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}"
          exitcode="0"

          # Run all the tests if no job was specified
          if [ -z "${job}" ]; then
            output=$(./tools/trigger-integration-tests.sh "${branch}" 2>&1) || exitcode=$?
          else
            output=$(./tools/trigger-single-integration-test.sh "${job}" "${branch}" 2>&1) || exitcode=$?
          fi

          # Set the body as a Github Action Output so we can read it below
          echo ::set-output name=exitcode::"$exitcode"
          if [ "$exitcode" == 0 ]; then
            exit 0
          fi

          # Format the message for github
          # -----------------------------
          # -----------------------------
          prefix=' :x:

          ---
          Test launcher output:
          ```
          '

          suffix='
          ```
          '

          body="${prefix}${output}${suffix}"
          # -----------------------------
          # -----------------------------

          #
          # Escape newlines, special github comment voodoo, details:
          # https://github.com/peter-evans/create-or-update-comment#setting-the-comment-body-from-a-file
          #
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo ::set-output name=body::$body

      - name: Add reaction if everything went okay
        if: steps.run-the-tests.outputs.exitcode == '0'
        # v1
        uses: peter-evans/create-or-update-comment@41f3207a84f33bd70388036109082784d059dcaa
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray

      - name: Add stderr if exitcode != 0
        if: steps.run-the-tests.outputs.exitcode != '0'
        # v1
        uses: peter-evans/create-or-update-comment@41f3207a84f33bd70388036109082784d059dcaa
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: ${{ steps.run-the-tests.outputs.body }}
